name: "CI"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  ci:
    uses: braintree/web-sdk-github-actions/.github/workflows/ci.yml@2e28547bb521475009cfbae2bcc7bb0791f97ac0  # main
